### ISSUE TITLE
The client is unable to verify that the server is Elasticsearch.

### ISSUE THREAD

**Issue by mokhos** [bitnami/bitnami-docker-fluentd#37]
### Name and Version

bitnami/fluentd:1.14.5-debian-10-r33

### What steps will reproduce the bug?

1. Elasticsearch helmchart (17.9.16 as of today) of Bitnami is installed.
2. Fluentd helmchart (5.0.12 as of today) of Bitnami is configured to use elasticsearch plugin.

### What is the expected behavior?

Fluentd daemonset to be installed and running on K8s.

### What do you see instead?

A bunch of errors like this:

```
2022-03-25 15:31:10 +0000 [info]: adding match pattern="fluentd.healthcheck" type="stdout"
2022-03-25 15:31:10 +0000 [info]: adding match pattern="**" type="elasticsearch"
2022-03-25 15:31:11 +0000 [info]: Received graceful stop
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
2022-03-25 15:31:11 +0000 [error]: #0 unexpected error error_class=NoMethodError error="undefined method `+' for nil:NilClass"
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/excon-0.91.0/lib/excon/connection.rb:247:in `request'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `block in call'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.10.0/lib/faraday/adapter.rb:50:in `connection'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `call'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.10.0/lib/faraday/rack_builder.rb:154:in `build_response'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.10.0/lib/faraday/connection.rb:516:in `run_request'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elastic-transport-8.0.0/lib/elastic/transport/transport/http/faraday.rb:49:in `block in perform_request'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elastic-transport-8.0.0/lib/elastic/transport/transport/base.rb:298:in `perform_request'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elastic-transport-8.0.0/lib/elastic/transport/transport/http/faraday.rb:36:in `perform_request'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elastic-transport-8.0.0/lib/elastic/transport/client.rb:176:in `perform_request'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:161:in `elasticsearch_validation_request'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:85:in `verify_elasticsearch'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:70:in `method_missing'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-api-8.0.0/lib/elasticsearch/api/actions/info.rb:39:in `info'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:495:in `detect_es_major_version'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:487:in `block in handle_last_seen_es_major_version'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/elasticsearch_index_template.rb:56:in `retry_operate'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:484:in `handle_last_seen_es_major_version'
  2022-03-25 15:31:11 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:336:in `configure'
```

### Additional information

I already read [here](https://stackoverflow.com/questions/71274282/fluentd-elasticsearch-plugin-the-client-is-unable-to-verify-that-the-server-is) that the issue might be because of inconsistency between "elastic 7.17.1" and "elasticseach plugin 8.0.0".
I am wondering, how is it possible that both helmcharts are coming from bitnami, but one is working with ES 7 and the other is installing ES 8 (if that is the case).

Any ideas how can I fix the issue?

**Comment by dansomething** [comment]
Same issue here. The elasticsearch v8 client installed with fluentd isn't compatible with the v7 server that gets installed by the Bitnami chart.

```
I have no name!@4fdf52ec53f4:/opt/bitnami/fluentd$ fluent-gem list | grep elastic
elastic-transport (8.0.0)
elasticsearch (8.0.0)
elasticsearch-api (8.0.0)
elasticsearch-xpack (7.17.1)
fluent-plugin-elasticsearch (5.2.0)
I have no name!@4fdf52ec53f4:/opt/bitnami/fluentd$ fluent-gem list | grep plugin
fluent-plugin-concat (2.5.0)
fluent-plugin-detect-exceptions (0.0.14)
fluent-plugin-elasticsearch (5.2.0)
fluent-plugin-grafana-loki (1.2.18)
fluent-plugin-kafka (0.17.4)
fluent-plugin-kubernetes_metadata_filter (2.9.4)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-out-http (1.3.3)
fluent-plugin-prometheus (2.0.2)
fluent-plugin-record-modifier (2.1.0)
fluent-plugin-rewrite-tag-filter (2.4.0)
fluent-plugin-s3 (1.6.1)
fluent-plugin-systemd (1.0.5)
```

**Comment by dansomething** [comment]
FYI, 1.14.5-debian-10-r1 was the last image with Elasticsearch 7.17.0

**Comment by migruiz4** [comment]
Hi,

I'm sorry for the inconvenience. We are working to release the Elasticsearch 8 image and chart as soon as possible.

In the meantime, it will be necessary to use an earlier version of the Fluentd image.

**Comment by mokhos** [comment]
> Hi,
> 
> I'm sorry for the inconvenience. We are working to release the Elasticsearch 8 image and chart as soon as possible.
> 
> In the meantime, it will be necessary to use an earlier version of the Fluentd image.

Thanks for your response. Would you please name the version which is compatible with ES 7.17.1?

**Comment by migruiz4** [comment]
As @dansomething commented, `1.14.5-debian-10-r1` is the latest image with the Elasticsearch ruby gem 7.17.0.

If I'm not mistaken it should also work with Elasticsearch 7.17.x patch releases, including `7.17.1`.

**Comment by mokhos** [comment]
Hi @dansomething, did you test it with 1.14.5-debian-10-r1 ?

I still get almost same errors.

**Comment by dansomething** [comment]
Yes, I was able to get it to work with `--set image.tag=1.14.5-debian-10-r1`

**Comment by dansomething** [comment]
Well, I thought it was working, but I'm actually getting a different error now. It's still failing to send logs to Elasticsearch.  Perhaps it's still a compatibility issue or it could just be my config.

**Comment by mokhos** [comment]
I'm not getting anything regarding compatibility, but some errors like so:


```
2022-03-28 14:46:06 +0000 [info]: adding match pattern="fluent.**" type="null"
2022-03-28 14:46:07 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2022-03-28 14:46:07 +0000 [warn]: #0 !! The environment variable 'K8S_NODE_NAME' is not set to the node name which can affect the API server and watch efficiency !!
2022-03-28 14:46:07 +0000 [info]: adding match pattern="fluentd.healthcheck" type="stdout"
2022-03-28 14:46:07 +0000 [info]: adding match pattern="**" type="elasticsearch"
2022-03-28 14:46:08 +0000 [info]: Received graceful stop
2022-03-28 14:46:09 +0000 [error]: #0 unexpected error error_class=NoMethodError error="undefined method `+' for nil:NilClass"
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/excon-0.91.0/lib/excon/connection.rb:247:in `request'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `block in call'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.9.3/lib/faraday/adapter.rb:50:in `connection'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `call'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.9.3/lib/faraday/rack_builder.rb:154:in `build_response'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.9.3/lib/faraday/connection.rb:516:in `run_request'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-transport-7.17.0/lib/elasticsearch/transport/transport/http/faraday.rb:50:in `block in perform_request'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-transport-7.17.0/lib/elasticsearch/transport/transport/base.rb:289:in `perform_request'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-transport-7.17.0/lib/elasticsearch/transport/transport/http/faraday.rb:36:in `perform_request'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-transport-7.17.0/lib/elasticsearch/transport/client.rb:197:in `perform_request'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-7.17.0/lib/elasticsearch.rb:93:in `elasticsearch_validation_request'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-7.17.0/lib/elasticsearch.rb:51:in `verify_elasticsearch'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-7.17.0/lib/elasticsearch.rb:40:in `method_missing'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-api-7.17.0/lib/elasticsearch/api/actions/info.rb:37:in `info'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:498:in `detect_es_major_version'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:490:in `block in handle_last_seen_es_major_version'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/elasticsearch_index_template.rb:52:in `retry_operate'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:487:in `handle_last_seen_es_major_version'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:339:in `configure'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin.rb:187:in `configure'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:132:in `add_match'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:74:in `block in configure'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `each'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `configure'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:149:in `configure'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:105:in `configure'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:80:in `run_configure'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:716:in `block in run_worker'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:968:in `main_process'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:708:in `run_worker'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/command/fluentd.rb:372:in `<top (required)>'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/bin/fluentd:15:in `<top (required)>'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/bin/fluentd:23:in `load'
  2022-03-28 14:46:09 +0000 [error]: #0 /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
2022-03-28 14:46:09 +0000 [info]: Worker 0 finished with status 1


```

It's like some coding errors

**Comment by dansomething** [comment]
That does appear to be a request failure do your Elasticsearch instance. FWIW, here's my Elasticsearch version info.
```
$ curl http://localhost:9200
{
  "name" : "elasticsearch-coordinating-only-0",
  "cluster_name" : "elastic",
  "version" : {
    "number" : "7.16.1",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "5b38441b16b1ebb16a27c107a4c3865776e20c53",
    "build_date" : "2021-12-11T00:29:38.865893768Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by migruiz4** [comment]
I found this issue that looks very similar to what you shared @mokhos 

https://github.com/uken/fluent-plugin-elasticsearch/issues/561

Maybe there is an issue with the elasticsearch output configuration.

**Comment by mokhos** [comment]
Thanks for the hint @migruiz4 

I guess the issue is now with my ELASTICSEARCH_HOST. 
It does not accept "elasticsearch-master.logging.svc.cluster.local" as the value for ES host.

**Comment by mokhos** [comment]
@dansomething Would you please tell me about the values of your ELASTICSEARCH_HOST or FLUENT_ELASTICSEARCH_HOST ?

I'm now getting this error:

```
/opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin/out_forward.rb:745:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
```
Sounds like anything I gave it, cannot to be read by fluentd. I've tried these values:
"elasticsearch-master.logging.svc.cluster.local"

"elasticsearch-master-0.elasticsearch-master.logging.svc.cluster.local, elasticsearch-master-1.elasticsearch-master.logging.svc.cluster.local, elasticsearch-master-0.elasticsearch-master.logging.svc.cluster.local"

"elasticsearch-master"

**Comment by dansomething** [comment]
We're using the elasticsearch-coordinating-only service.

```yaml
aggregator:
  configMap: fluentd-aggregator-cm
  extraEnvVars:
    - name: ELASTICSEARCH_HOST
      value: elasticsearch-coordinating-only.elasticsearch.svc.cluster.local
    - name: ELASTICSEARCH_PORT
      value: "9200"
```

The Fluentd forwarders send to the Fluentd aggregator which sends to Elasticsearch.

**Comment by dansomething** [comment]
Perhaps it's still a config issue? Here's our full forwarder (the DaemonSet) configmap for reference.
```yaml
    <system>
      log_level info
    </system>

    # Ignore fluentd own events
    <label @FLUENT_LOG>
      <match fluent.**>
        @type null
      </match>
    </label>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>

    # Ignore the fluentd logs to avoid recursion
    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>

    # TODO This should probably be removed so we can keep kube system logs
    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>

    # Json Log Example:
    # {"log":"[info:2016-02-16T16:04:05.930-08:00] Some log text here\n","stream":"stdout","time":"2016-02-17T00:04:05.931087621Z"}
    # CRI Log Example:
    # 2016-02-17T00:04:05.931087621Z stdout F [info:2016-02-16T16:04:05.930-08:00] Some log text here
    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

    # Concatenate multi-line logs
    <filter **>
      @id filter_concat
      @type concat
      key message
      multiline_end_regexp /\n$/
      separator ""
    </filter>

    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>

    # Fixes json fields in Elasticsearch
    <filter kubernetes.**>
      @id filter_parser
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>

    # Send to STDOUT for debugging
    #<match **>
    #  @type stdout
    #</match>

    # Forward all logs to the aggregators
    <match **>
      @type forward
      <server>
        host fluentd-0.fluentd-headless.fluentd.svc.cluster.local
        port 24224
      </server>

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>
```

**Comment by mokhos** [comment]
> Here's our full forwarder (the DaemonSet) configmap for reference.

I don't understand, where did you set the elasticsearch plugin then.
I mean regarding what we have in [chart's reference](https://artifacthub.io/packages/helm/bitnami/fluentd/5.0.0#forwarding-the-logs-to-another-service).

**Comment by dansomething** [comment]
With the Bitnami Helm chart, the DaemonSet forwards to the aggregator StatefulSet. Here's our config for that.
```yaml
    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>

    # get logs from syslog
    <source>
      @type syslog
      port 42185
      tag syslog
    </source>

    # TCP input to receive logs from the forwarders
    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>

    # Send the logs to the standard output
    <match **>
      @type elasticsearch
      include_tag_key true
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      logstash_format true
      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>
```

**Comment by mokhos** [comment]
Finally found the issue. In my case the defined environment variables couldn't be passed to the elasticsearch plugin for some unknown reason. I used the real values instead of environment variables and now it is working.
